name: Restrict Pull Requests to Main

on:
  pull_request:
    branches:
      - main

jobs:
  restrict-main:
    runs-on: ubuntu-latest
    steps:
      - name: Check Base Branch
        if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref != 'dev'
        run: |
          echo "Pull requests to main are only allowed from dev"
          exit 1
